### ISSUE TITLE
No running server found

### ISSUE THREAD

**Issue by shokimble** [Kismuz/btgym#1]
Hi,

Great work. 

I was looking for examples of market trading environments for OpenAI for an idea I had around machine learning for risk management (I don't think you can teach a computer to trade on random walk data better than you can teach a human - it's like locking both in a box and hoping they can make money) but what I am hoping you can do is teach them risk management/position sizing based on prevailing market conditions which has much more useful applications.

Hooking OpenAI into Backtrader turns out to be more than I could hope for.

Just one issue I ran into which might be worth noting for others or updating your documentation...

When running your examples they all (or at least all the ones I tried) log "No running server found." then exit.

The issue is that you haven't got an agent running. It might be worth demonstrating a basic agent. Eg:

env = ..........
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

**Comment by Kismuz** [comment]
0. Be sure to update by `git pull` as changes are made almost every day.
1.  "No running server found."  message is ok when making environment since servers autostart when calling env.reset() for first time.
2. Take a look at https://github.com/Kismuz/btgym/blob/master/examples/setting_up_environment_basic.ipynb
for basic random agent loop.
3. To mention, no env.render() implemented yet.

**Comment by Kismuz** [comment]
Changed message to be less confusing.

**Comment by Kismuz** [comment]
Changed message to be less confusing.

**Comment by Kismuz** [comment]
Basic env rendering implemented.
Example notebook updated.
