### ISSUE TITLE
Get better signal strengths by tuning scaling hyperparameters

### ISSUE THREAD

**Issue by ryanle88** [Kismuz/btgym#35]
Hi @Kismuz 
I need your help to clarify a few questions:
1. Currently, Unreal Stacked LSTM Strat 4_11 has better performance on actual FOREX prices than A3C Random, so just out of curiosity, I tried to run both of them with the sine wave data (test_sine_1min_period256_delta0002.csv). It turns out that A3C eventually converges while Unreal Stacked LSTM is nowhere near the convergence. Could you provide me some insights on that?

LSTM results:
![image](https://user-images.githubusercontent.com/5439020/35714937-363a69fe-0795-11e8-9be3-5f76481a3893.png)
![image](https://user-images.githubusercontent.com/5439020/35714949-4b1eace0-0795-11e8-9192-40cef7bf95aa.png)

A3C results:
![image](https://user-images.githubusercontent.com/5439020/35714967-5efbbfdc-0795-11e8-9c74-ebb12badb0b6.png)
![image](https://user-images.githubusercontent.com/5439020/35714976-6979bd7e-0795-11e8-84a4-a468d9a23b74.png)

2. I had an overflow issue with the tanh(x_sma) while feeding my own data into the gym (SPY, Dow Jones, Russel 2000, and so on). After changing the T2 value from 2000 to 1, the issue went away but I am not sure if that was a proper fix. Could you help me shed some lights on that?

3. I also got data consistency issue when passing equity data traded from 8:30am to 15:15pm instead of 24/7 like FOREX data that you used as examples. What should I do to fix this?

4. I kept getting the "[WinError 2] The system cannot find the file specified" when trying to run the A3C example in Windows.
![image](https://user-images.githubusercontent.com/5439020/35715280-13dc44c0-0797-11e8-8867-10364a7fc310.png)

5. When I tried to run the A3C with the new version of tensorflow supporting GPU in Windows, I I got the error below also:
![image](https://user-images.githubusercontent.com/5439020/35715384-a9a3b5e2-0797-11e8-8d2e-74816f69a0d7.png)

![image](https://user-images.githubusercontent.com/5439020/35715401-b59de750-0797-11e8-8429-0c09097ac6eb.png)

Really appreciate your effort to build this awesome gym and great documentation.

Thank you in advance.

**Comment by Kismuz** [comment]
1. If you mean running `unreal_stacked_lstm_strat_4_11.ipynb` on sine data `test_sine_1min_period256_delta0002.csv` - I can confirm it converges almost instantly (less than 20K iterartions). I advise to update package as some minor tweaks has been made recently. Have you done any alterations to code which can result divergence?

2. Yes, it is exactly the way to adjust signal strength. To verify if it has proper amplification  pay attention to tensorboard image of the state:
<img src="./btgym/blob/master/examples/img/tb_obs_2018-02-02.png" width="400">

![Pic](https://github.com/Kismuz/btgym/blob/master/examples/img/tb_obs_2018-02-02.png)

... and you can also change rendering options in notebook: set `env_config['kwargs]['render_state_as_image']` to `False` to visually inspect curves: if they get "squared" by tanh - lower T param value. It is better have signal under- than over-amplified. In this case most of the spikes fit in almost linear part of tanh while compressing outliers.

3. Quick fix is to rise value for `time_gap` param to cover empty time periods. You can run `btgym.datafeed.test_data.py` (alter dataset params to you needs) to see if it passes ok to save time.

4.. win again... sims it is os specific `glob` implementation (it used to compose system path string). Unfortunately can't replicate, do not have that os installed.

5. Seems tf import error, can't comment on that. Does your tf installation works ok on other tasks?

**Comment by ryanle88** [comment]
@Kismuz 
Thank you for your quick response! 
1. The only code that I changed was the initial cash amount from 2,000 to 100,000. I got the latest of your code and reran the LSTM notebook for both of them. It converged for the 2,000 but not 100,000. Rather strange to me. Not sure if the signal strength had anything to do with that.

2. I have a better understanding about this graph now since before I did not know how to read it.
![image](https://user-images.githubusercontent.com/5439020/35752755-c6fbd2ec-0822-11e8-8640-883275c1593b.png)

3. I'll test it today with your suggestions and let you know if I can figure it out.

5. It is my fault. I installed the nightly version, which came with the bug. The import statement works now with the release version 1.5 of tensorflow (GPU).

**Comment by Kismuz** [comment]
@ryanle88:
> The only code that I changed was the initial cash amount from 2,000 to 100,000. I got the latest of your code and reran the LSTM notebook for both of them. It converged for the 2,000 but not 100,000. Rather strange to me. Not sure if the signal strength had anything to do with that.

well, because changes in  initial cash amount require appropriate changes in stake size. Otherwise max profit /max loss margins (wich are set in precentage to initial cash) became bigger and within episode time span given it is impossible to make significant changes to broker account value --> no noticeable changes in broker statistic --> no proper reward estimation (cause reward terms got normalised wrt max possible profit/loss values) --> agent gets confused :)

>I have a better understanding about this graph now 

may be more convenient:
```
env_config = dict(
    class_ref=BTgymEnv, 
    kwargs=dict(
        .......
        render_state_as_image=False,
        .......
    )
)

```

**Comment by ryanle88** [comment]
Thank you for the detailed explanation, @Kismuz !

        Quick fix is to rise value for time_gap param to cover empty time periods. You can run 
        btgym.datafeed.test_data.py (alter dataset params to you needs) to see if it passes ok to save time.

So I went back and try to change the time_gap as you recommended and it works. What I am still not very clear is that the maximum number of day difference in my dataset is 5 days but I have to set the time_gap at least 7 days and 1 hour to make it work (no data consistency error). Is it correct?

I also tried to play around with the btgym.datafeed.test_data.py as you suggested but couldn't make it work at all. Wondering if you could explain these terms (trial_params, episodes_params, target_period, sample_duration, and episode_duration) and how they are connected since I went over your code and read the comments you wrote about them but still did not click for me yet.

One thing I realized while modifying the time_gap is that its value could impact how the agent learned. When I set the time_gap >= 8 days, the agent learned pretty well compared to when it is set to 7 days. Not sure why there is a large difference like that.

Also should the final value of all the trained agents start at the same spot (initial cash)? Did I do anything wrong?

![image](https://user-images.githubusercontent.com/5439020/35763260-e123a65e-086d-11e8-8735-53e13d04987e.png)

The next question I have is: what is the best way to tune T, initial cash and stake to get the best signal strength? Trial and error? 
What happens when I wanted to include other stocks and indices with large differences in values (AMD: 12.45, FB: 190, GOOG: 1111, ^GSPC: 2762). What should be the T value? Should I normalize the data before feed them into the gym?

To make it even more realistic, what if I wanted to add a couple of technical indicators (SMA, Stochastic, Bollinger Bands)? What should I do to find the optimal state representation with my available data set (SMA30, SMA60, SMA90, SMA180)? Should I run it through PCA or CNN first?

Really appreciate for taking your time to help me. If you need some help with minor tasks like update the documentation for btgym or the like, please let me know.

Thank you again.

**Comment by Kismuz** [comment]
@ryanle88 , 
> what is the best way to tune T, initial cash and stake to get the best signal strength? 

**initial cash, stake and leverage** are pure trading arithmetic; one should put agent in sensible conditions i.e. goal set should be reachable; as sanity check of your broker setup, randomly acting agent should be able to drain your trading account in at least ~2/3 of maximum episode duration; should be able to make at least one stake etc. 
See also: #36

**Signal scaling and preprocessing**:
I tried not to use z-normalisation, pca, whitening etc due to reason all of those depend on your dataset distribution and work well when later is stationary, like as assumed in supervised/unsupervised learning. Here we get non-stationary distribution of states, so it is make sense to use methods which itself are not conditioned on data. 
To center signal, finite differences used, than scaled and bound by passing through non-linearity. 
Im' not saying it is best method. It  worth  checking how much dataset statistics drift with time. If drift is minimal, maybe it is ok to say stat is stationary and use PCA etc. Good direction for research btw.
To illustrate effect of scaling parameter I prepared and pushed notebook, check it out:
https://github.com/Kismuz/btgym/blob/master/examples/state_signal_scaling.ipynb
 - made scaling a strategy kwarg parameter - easy to experiment; 
- note that entire dataset  and current episode statistic are accessible as pandas dataframes from startegy via `self.p.dataset_stat, self.p.episode_stat` attributes so you can use to, say, z-normalize data.

Btw, working on this notebook revealed I have missed a bit with T, so now it is `state_ext_scale = 1e3` by default for SMA-based signal strategies.

...will comment on other questions later.

**Comment by tmorgan4** [comment]
@ryanle88 

If you haven't already I would suggest looking at a book called "Statistically Sound Machine Learning for Algorithmic Trading of Financial Instruments: Developing Predictive-Model-Based Trading Systems Using TSSB".  

[https://www.amazon.com/Statistically-Learning-Algorithmic-Financial-Instruments/dp/148950771X](url)

Much of the book is written as a user manual for their (free) software called TSSB but if you're able to think outside the box there is an enormous amount of good information on statistics, normalization of data/indicators, feature selection, rules of thumb, etc.  Obviously it requires a mathematical background but it's nowhere near as difficult to read as many of the machine learning papers with complicated notation and proofs.  I'm quite surprised the book hasn't received much attention but I think many of the poor reviews were expecting a plug-and-play recipe for a profitable trading system and that's not what inside.  

@Kismuz if you haven't read it and think you would I'd gladly try and get a copy to you as a thank you for your work on this project.  Can't remember where you're located.

This is the link to the actual user manual for the software.  The book covers much of the same material and a bunch more.  [http://www.tssbsoftware.com/tssb_download/tssb%20user%20manual%201.55.pdf](url)

**Comment by ryanle88** [comment]
@Kismuz Thank you for creating the state signal scaling notebook! It is awesome. Save a lot of time getting the signal strength just right before feeding the data into the gym.
![image](https://user-images.githubusercontent.com/5439020/35774869-f146d4aa-0941-11e8-8e19-f4f72f2b3d58.png)

@tmorgan4  Thank you for the recommendation.

**Comment by Kismuz** [comment]
@tmorgan4 , really appreciate you offer; I came across this book some tome ago and can confirm it is good cookbook for tasks discussed as well as some others. It was one of the sources that gave me inspiration to work with wavelet transforms as one preprocessing technique; my early btgym preprocessing was based on CWT with ricker wavelet; later I replaced it with temporal convolutions but it gave some valuable insights.  Btw I live in  Moscow, RU.

**Comment by Kismuz** [comment]
@ryanle88, I made and pushed some simple updates to notebook and it reveals we got problem here: when plotting signal distribution on per channel basis it comes clear it is essential to apply weighted scaling. That answers my empirical observation (counterintuitive ) that over-sclaing brings faster convergence :/ Should been paying more attention to it. Clearly there is room for improvement.

**Comment by ryanle88** [comment]
Thank you for the update @Kismuz ! This makes more sense to me since we need different scaling for different equities with different levels of magnitude. Are you planning to make the change in the near future? Or should I create a strategy method which inherits from the base strategy and make the change according in the meantime?

**Comment by Kismuz** [comment]
@ryanle88 ,
I would not touch base method until absolutely necessary as it merely serves as template; observation an reward it computes can be considered dummy ones; subclassing it is suggested method for doing research work. Btgym `research` sub-package is proper place to put it in. You can browse` btgym.research.strategy_gen_4.py` to see evolving classes hierarchy and how, say, reward function or observation space computations has been shaped; making such prototypes (along with proper git branching) brings flexibility; it is easy to separate effects of changes been made or roll back if something went wrong. 
When your research is done and proved useful it can be collapsed to single class and moved to one of main stable sub-packges;

**Comment by ryanle88** [comment]
@Kismuz 
Sorry for not being clear. What I meant is exactly what you just suggested since I don't want to directly make any changes to your code which may cause trouble later on when performing a git pull.
![image](https://user-images.githubusercontent.com/5439020/35781717-448aefcc-09b3-11e8-9a59-5ab4ad7e412c.png)

**Comment by Kismuz** [comment]
@ryanle88, it is those three first shapes that looks confusing to you?

I'll try to loosly formulate what-is-for:
State composition intuition is as follows: 

**First**, we take set of signal statistics which are 'similar' but differs in time scale; here signal statistic is plain SMA and time-scaling factor - sma period.We want to get a matrix of somehow encoded information about relatively long signal period (cause to compute one sma256 value you need 256 previous signal values, 32 for sma 32 etc.) Than we take, say, 30 last values of every statistic to form a matrix. It bears information from last 256 signal values but encoding gets 'coarsier' from present time to -256'th point; this is similar to 'temporal-convolution' idea. So, again those statistics should be of any single type (sma, oscillators, wavelet transforms, windowed fourier transforms etc. ) and should differ in one scale only;

**Second**, we take one step differences along _features_ axis, we don't want to touch time axis yet (will do it later). Taking one-step difference (np.gradient that is no more than finite differences with smoothing and fancy endpoints treatment)  removes trends, centers and stabilises signal; after this operation we can no longer eyeball signal but neural net will be happy with it; At this point we perform scaling to get more consistent distribution across channels(now can call it _hard-coded low-level features_). Tanh here is pure elastic scaling and can be thought of as 'compressing dynamic band' of your signal to fight outliers.

Now we get our state as  'vector in time-features space', and it is long in time dimension (say, 30) and short in features dimension (say, 5). And this vector represents _single_ observation state of POMDP. To feed it to [possibly context-aware] policy estimator we want compress and reshape it to be short in time dimension (1) and long along features dimension (~64) 

So, **third**, we pass it through convolutional encoder of our LSTM agent; unlike with images, we convolve along single time dimension(4 layers) and at the end we get a 64 kernels activations and those activations can be thought as _learned_ features representation of our once-was-time-embedded state (actually we get 2x64 features, but it is ok). Now we can pass it forward to RNN, feedforward net or linear classifier of choice to get policy, values etc.

**Looking at your code** it is clear that first three stats are not from the same field as rest. Ok, Open value can be thought as SMA-1, but Low is always lower [than Open and Close] and High is, well, higher. So when we take differences along statistics axis, first channel will consist of only positive differences, second and third  - only negative ones; that's why you get 'halved' distributions.

If your aim is to bring more 'resolution' to state I suggest stacking Open-Sma2-Sma4-... 
or can use HL median instead of Open: HL = (High+Low)/2; using full OHLC is redundant imho.

**Comment by ryanle88** [comment]
@Kismuz 
Yes, the first three distributions are those that confused me. I am still in the process of exploring to find the right state representation that I can work with based on the information that I have available. Thank you for providing such a detailed explanation. Really appreciate that!!

**Comment by ryanle88** [comment]
@Kismuz 
I have spent sometime in the past two days to explore different state representations to see if I can find anything useful. My rationale was that whatever information is required for a human to have to make an informed decision is also required for a machine to have to make its own decision since the machine is just a lot better in memory and speed than us, not in logical thinking and decision-making process. 

For example, for atari games, we humans only need to see the screen progress to make the decision whether to move up or down, left or right, that is why reinforcement learning technique performs so well on those games by feeding four consecutive screenshot pixels to the neural networks. 

However, in trading, it is a lot more complicated since trader cannot make a trading decision based on solely the historical prices of OHLC. Depending on the type of trades, the trader needs to see many different things before making the decision on the type of strategy that he/she wants to proceed: S&P500, Dow Jones, Russell 2000, VIX, the date of week, current month, earning announcement dates, price distribution of the underlying, Bollinger Bands, TTE Squeeze signal, and many more. 

Therefore, I tried to add extra technical indicators (besides SMAs) like Stochastic, ATR, Momentum Oscillator, CrossOver, Bollingers Band, and some of the EFTs like DIA, FXB, GLD, SPY, TLT, UNG, and so on. However, they did not work as I expected because of the signal strengths. Some of the indicators and EFTs have values way higher than the value that I tried to predict, so I did not get the proper signal strengths for the agent to learn (as you explained above).

![image](https://user-images.githubusercontent.com/5439020/36009766-58336686-0d13-11e8-9bef-4255cfc506a2.png)
![image](https://user-images.githubusercontent.com/5439020/36009773-6633940e-0d13-11e8-951c-5dbe2d0cb1d5.png)

At this point, I am not sure how to move forward with this, but will keep learning and exploring in the meantime to see how other fields can overcome this type of challenge.

This is just an FYI. Keep up the good work!!

**Comment by Kismuz** [comment]
@ryanle88 

> My rationale was that whatever information is required for a human to have to make an informed decision is also required for a machine

Your idea is correct but implementation goes against principles I wrote about: for convolution network to learn relevant features signal should be somehow consistent across entire gradients field (see above). Personally I cant give any sensible judgment to signal differences from SMA values to Oscillator values; it is not about normalising, it is like comparing apples and horses; don't think it would work out this way.

>  I am not sure how to move forward with this

One way to start experimenting with new features is to structure it by putting every 'features bank' to separate convolution encoder; than concatenate  features learnt and feed entire _encoded state_ tensor to rnn estimator; so it can be sma-encoder, momentum_osc encoder etc. every one of them  taking matrix of same-type statistics in different timeframes;

>  that is why reinforcement learning technique performs so well on those games by feeding four consecutive screenshot pixels 

exactly, but not frames and sounds; if one have to he would encode pixels and audio separately

Please also see here: https://github.com/Kismuz/btgym/issues/23#issuecomment-348951755

**Comment by ryanle88** [comment]
Got you. Thank you for your help pointing out the directions, @Kismuz !

**Comment by JacobHanouna** [comment]
>>The only code that I changed was the initial cash amount from 2,000 to 100,000. I got the latest of your code and reran the LSTM notebook for both of them. It converged for the 2,000 but not 100,000. Rather strange to me. Not sure if the signal strength had anything to do with that.

>well, because changes in initial cash amount require appropriate changes in stake size. Otherwise max profit /max loss margins (wich are set in precentage to initial cash) became bigger and within episode time span given it is impossible to make significant changes to broker account value --> no noticeable changes in broker statistic --> no proper reward estimation (cause reward terms got normalised wrt max possible profit/loss values) --> agent gets confused :)

>initial cash, stake and leverage are pure trading arithmetic; one should put agent in sensible conditions i.e. goal set should be reachable; as sanity check of your broker setup, randomly acting agent should be able to drain your trading account in at least ~2/3 of maximum episode duration; should be able to make at least one stake etc.

Going over this post got me thinking on what will be the effect on markets that have a huge price moments (like the crypto market)? the ratio between a fix size stack and the initial cash will vary greatly between episodes. which I assume will get the agent 'confused'.

I checked the code to see if there is a way to deal with the issue. I guess that if I set `portfolio_actions = {}` it will force the system to use a continues action (that is percentage based). but this way we lose simplicity of discrete actions.

What will be the proper way to deal with such scenario?

**Comment by tmorgan4** [comment]
@JacobHanouna 
You're on the right track and it's one of many issues that needs to be dealt with in a non-stationary time series.  For this specific issue I'd suggest looking into the backtrader PercentSizer.  Instead of each trade being a fixed number of shares or contracts (or bitcoin) the size of the trade is now a % of your cash.  Make sure to consider the effects this could have on return (i.e. does the volatility vary as a % of price or is it a fixed value)? An easier example to visualize is the way a $1000/share stock can flunctuate $50 in a day but you'd be less likely to see this behavior from a $100 stock.  This is why you often see prices being scaled by log(price).
    
https://www.backtrader.com/docu/sizers-reference.html

**Comment by JacobHanouna** [comment]
@tmorgan4 thank you for replying.

Just to confirm and that the answer will be complete if anyone comes across the same issue
I can add `cerebro.addsizer(bt.sizers.PercentSizer, percents=25)` to the cerebro instance, that will go into the env config and make sure `order_size=None` is set in the `cerebro.addstrategy(...). this will change BTGym behavior to use a percentage type sizer. right?

**Comment by JacobHanouna** [comment]
I ran some tests with this setup. Agent behavior is not 100% clear.

this is the code in base strategy:
```
 # Try to define stake, if no self.p.order_size dict has been set:
        if self.p.order_size is None:
            # If no order size has been set for every data_line,
            # try to infer stake size from sizer set by bt.Cerebro.addsizer() method:
            try:
                assert len(list(self.env.sizers.values())) == 1
                env_sizer_params = list(self.env.sizers.values())[0][-1]  # pull dict of outer set sizer params
                assert 'stake' in env_sizer_params.keys()
```
from the code it can be understood that setting `order_size=None` will make BTGym look for implicit definition to `bt.Cerebro.addsizer()` by the user. 
but the problem is that `bt.sizers.PercentSizer` doesn't have a 'stack' param. so the `assert` will raise an error. commenting out the assert doesn't help because later in the code BTGym is expecting 'stack' key so an error will happen anyway.

I tried to make `order_size=percents` and it seem to work fine (checked that it is indeed 25% on tensorboard) but then we completely override this piece of code.

So it is a bit of a workaround but the behavior of the code is ambiguous

**Comment by Kismuz** [comment]
@JacobHanouna, this has been made for fixed stakes; indeed, it looks for a dictionary of sizers corresponding every asset traded; if not found - uses single value added by .addsizer for all.
It's a bit outdated anyway in sense that as it turns out it much more flexible to estimate and explicitly set order size when submitting individual orders by setting `size` kwarg (as well as asset).

**Comment by Kismuz** [comment]
**UPDATE ON SIGNAL SCALING**:
after playing with different preprocessing/scaling/normalising routines it seems that one simple solution based on std normalisation is quite robust to different levels of price or volatility regimes and requires no manual tuning. 
Implementation is here: https://github.com/Kismuz/btgym/blob/master/btgym/research/model_based/strategy.py#L189

**Comment by JacobHanouna** [comment]
@Kismuz can you please explain your above statement? I thought that order_size is fix amount for the whole run
>It's a bit outdated anyway in sense that as it turns out it much more flexible to estimate and explicitly set order size when submitting individual orders by setting size kwarg (as well as asset).

**Comment by JacobHanouna** [comment]
So if I understand correctly we need to set order_size so the system have some default, but a better option is to control it from the strategy end point

>you can choose to estimate optimal (in some sense) single order size
sound like order_size should be learned as part of the network outputs

**Comment by Kismuz** [comment]
> ...a better option is to control it from the strategy end point

exactly

> order_size should be learned as part of the network outputs

optimal order sizing is one of future research directions; related and promising line is to learn optimal limit-orders placing instead of using market orders (expensive and less efficient in practice).

**Comment by JacobHanouna** [comment]
>UPDATE ON SIGNAL SCALING:
after playing with different preprocessing/scaling/normalising routines it seems that one simple solution based on std normalisation is quite robust to different levels of price or volatility regimes

@Kismuz I'm modifying [`MonoSpreadOUStrategy_0`](https://github.com/Kismuz/btgym/blob/master/btgym/research/model_based/strategy.py#L198) to work with more indicators beside SMA. What I'm trying to understand is how to generalize the solution properly? especially the scaling operation

I have some question regarding the scaling code:
```
scale = 1 / np.clip(self.data.std[0], 1e-10, None)
x_sma *= scale
dx = np.gradient(x_sma, axis=-1)
```
1. isn't `scale` equivalent to just => 1 / max(self.data.std[0], 1e-10)? (self.data.std[0] is just a scalar)
2. going over the mathematical definition of Standardization from [Wikipedia](https://en.wikipedia.org/wiki/Feature_scaling) => x' = (x - mean(x))/ std, aren't we lacking the mean(x) part? or in some way the gradient is filling the gap?
something like:
```
def set_datalines(self):
     self.data.mean= btind.SimpleMovingAverage(self.data.open, period=self.p.time_dim)
...
def get_external_state(self):
     # each element in feature should be subtract by self.data.mean[0] 
     # and then the result multiplied by the scale factor? 
```
3. if I want to use other indicators let's say for example RSI, I assume I need to find the RSI standard deviation separately and then apply the same type of solution used for SMA? but then it means not all features would have the same magnitude (RSI is between 0-100), is it even important? 
something like:
```
self.data.rsi = btind.RSI(self.data.open, period=16)
self.data.rsi_std = btind.RSI(self.data.rsi, period=self.p.time_dim)
```
4. a bit off topic but is there a reason you are using `self.data.open` instead of `self.data.close`?

**Comment by Kismuz** [comment]
@JacobHanouna,

> isn't scale equivalent to just => 1 / max(self.data.std[0], 1e-10)?

yes, exactly; it's just my personal preference to use np.clip() for numerical issues handling

> aren't we lacking the mean(x) part 

yes, we are. Note that we don't actually aim for full Z-score normalisation 'cause we use differencing operator afterwards. Think best way to get sense of it  is to try this option and see how it affects the performance;

> find the RSI standard deviation separately

think, yes 'cause that's quite another type of a signal. I further suggest using separate convolution encoders for any other type of features; lstm_policy class can easily handle this case if properly specified observation space is received;

> reason you are using self.data.open instead of self.data.close

no any specific reason.

**PS:** observation and statistics variance scaling is quite an important issue and definitely should be thought upon in a sense that price volatility (~observation variance) is not only normalisation statistic but also the first important factor of asset potential profitability itself; than it make sense to scale potential max profit/loss bounds and [possibly] reward function w.r.t. [rolling] variance of tradable asset. As for now, max_profit and max_drawdown limits are set manually which is not optimal. I'm working on it and will let know of any new results.

**Comment by JacobHanouna** [comment]
>Note that we don't actually aim for full Z-score normalisation 'cause we use differencing operator afterwards.Think best way to get sense of it is to try this option and see how it affects the performance;

@Kismuz thanks for the clarifications. 

The way I look at it, the std scale factor make the data unitless and subtracting mean shift the data to be  zero based. both seem to be impotent especially when starting to mix different types of data. making apples and oranges more comparable.
I have modified the code to include the mean value for full Z-score normalization and currently testing it. Will post my conclusions once it finish the run.

**Comment by JacobHanouna** [comment]
>I further suggest using separate convolution encoders for any other type of features

is it done by adding a new entry in state_shape (and adding a corresponding get_<new entry>_state)?

**Comment by Kismuz** [comment]
@JacobHanouna , yes, in particular by making `external` state shape  nested dictionary itself. Look at the example here:
https://github.com/Kismuz/btgym/blob/master/btgym/research/casual_conv/strategy.py#L541
and 
https://github.com/Kismuz/btgym/blob/master/btgym/research/casual_conv/strategy.py#L682

think of every asset specified as different feature bank; 

Also note policy kwarg `share_encoder_params` telling either encoders variables should be shared or not (sensible to set True if all data streams are of similar type):

https://github.com/Kismuz/btgym/blob/master/btgym/algorithms/policy/stacked_lstm.py#L33

**Comment by JacobHanouna** [comment]
>Also note policy kwarg share_encoder_params telling either encoders variables should be shared or not 

is there a difference between multiple encoders with shared params (with partial input space) and a single encoder (with all the input space)?

**Comment by JacobHanouna** [comment]
>in particular by making external state shape nested dictionary itself

@Kismuz  just to clarify the process of separating encoders, 
Is it required to have external state shape as a nested dictionary? or is it sufficient to just return a dictionary from get_external_state() in order to have separate encoders?

**Comment by Kismuz** [comment]
@JacobHanouna ,
yes, it is required to declare shape as nested dict AND it is ok  to return a dictionary from get_external_state()  since I haven't implemented automatic nested methods lookup, see:

https://github.com/Kismuz/btgym/blob/master/btgym/research/casual_conv/strategy.py#L544

and

https://github.com/Kismuz/btgym/blob/master/btgym/research/casual_conv/strategy.py#L682
